### PR TITLE
gitignore: don't ignore patch files

### PR DESCRIPTION
**Pull request by bspguy**
This is necessary for maintaining the two syvinitscript.patch files located in: 
		1. meta-adi-xilinx/recipes-support/adrv9009-zu11eg-fan-control-daemon/files/ 
		2. meta-adi-xilinx/recipes-support/libiio/files/

### CODE REVIEW

**Review by nunojsa — CHANGES_REQUESTED** [review]
Hi Roy,

Thanks for your patch. Can you please sign off your commit? Run `git commit` with `-s`. 

What do you mean "This is necessary for maintaining the two..."?

Also, please refactor your commit so it resembles the style used in the project. Something in the line:

```
gitignore: don't ignore patch files

Patch files are common in yocto and so, it makes no sense to ignore them.

```

**Comment by bspguy** [comment]
OK it is signed now.
My comment relates to the to patches which where not tracked by the repo.
This is exactly what this fix should resolve.
Anyway I think we mean the same thing.
I edited the commit message as you suggested.
Thanks!
Roy

**Comment by nunojsa** [comment]
> This is exactly what this fix should resolve.
Anyway I think we mean the same thing.

Yes, not sure what my younger me was thinking as patches are a very common way to bring changes into recipes...

**Comment by nunojsa** [comment]
> This is exactly what this fix should resolve.
Anyway I think we mean the same thing.

Yes, not sure what my younger me was thinking as patches are a very common way to bring changes into recipes...

As for the commit please just squash everything in one commit as this PULL should only be one commit. Then, force-push to update the PULL. Also, please remove the tab in the commit message after the title.

**Comment by bspguy** [comment]
Hi
I've squashed it all into one commit.
Please review.
Thanks :)

**Review by nunojsa — APPROVED** [review]

**Pull request merged**
